export const COLUMNS: Array<{ id: string; name: string }> = [
    { name: "Beneficiary ID", id: "HLKc2AKR9jW" },
    { name: "HouseHold Code", id: "r10igcWrpoH" },
    { name: "Enrollment Date", id: "enrollmentDate" },
    { name: "Type(Comprehensive, Prevention)", id: "type" },
    { name: "District/City", id: "district" },
    { name: "Subcounty", id: "subCounty" },
    { name: "Parish", id: "orgUnitName" },
    { name: "Village", id: "Xkwy5P2JG24" },
    { name: "Household Head", id: "ExnzeYjgIaT" },
    { name: "Primary Caregiver", id: "nDUbdM2FjyP" },
    { name: "Date of Assessment", id: "eventDate" },
    { name: "Beneficiary Name", id: "huFucxA3e5c" },
    { name: "DOB", id: "dob" },
    { name: "Age", id: "age" },
    { name: "Age Group", id: "ageGroup" },
    { name: "Sex", id: "CfpoFtRmK1z" },
    { name: "Current Weight", id: "weight" },
    { name: "Risk Factor at enrolment", id: "" },
    { name: "Current Risk Factor", id: "" },
    { name: "Other Risk Factors", id: "" },
    { name: "Baseline Household Economic Status ", id: "" },
    { name: "Current Household Economic Status ", id: "" },
    { name: "Household status", id: "" },
    { name: "Member status", id: "" },
    { name: "Reasons for Exit", id: "" },
    { name: "Currently Enrolled in School (Y/N)", id: "" },
    { name: "Newly enrolled", id: "" },
    { name: "HIV_Status(+, /,?,  //+)", id: "" },
    { name: "OVC_TST ASSESS", id: "" },
    { name: "OVC_TST RISK", id: "" },
    { name: "OVC_TST REFER", id: "" },
    { name: "OVC_TST REPORT", id: "" },
    { name: "HIV test not required based on  HIV risk Assessment", id: "" },
    { name: "Unknown HIV status: other reasons", id: "" },
    { name: "Newly Reported HIV Positive (1 Yes, 0 No)", id: "" },
    { name: "Newly Tested HIV Positive (1 Yes, 0 No)", id: "" },
    {
        name: "Newly Tested HIV Positive initiated on ART (1 Yes, 0 No)",
        id: "",
    },
    { name: "On_ART_VL (1 Yes, 0 No)", id: "" },
    { name: "ART_No_VL", id: "" },
    { name: "Facility", id: "" },
    { name: "Date of ART initiation", id: "" },
    { name: "Client member status ", id: "" },
    { name: "Regimen", id: "" },
    { name: "OVC_VL Eligible (1 Yes, 0 No)", id: "" },
    { name: "Last Viral Load Date", id: "" },
    { name: "12 Months VLTest done (1 Yes, 0 No)", id: "" },
    { name: "6 Months VLTest done (1 Yes, 0 No)", id: "" },
    { name: "OVC_VLR (1 Yes, 0 No, Waiting )", id: "" },
    { name: "Viral Load Status (Suppressed, Non Suppressed, Waiting)", id: "" },
    { name: "Sample type", id: "" },
    { name: "Viral Load Copies", id: "" },
    { name: "OVC_VLS (1 Yes, 0 No))", id: "" },
    { name: "On multi month Dispensing (MMD) Y/N", id: "" },
    { name: "Client DSD model", id: "" },
    { name: "Client TB Preventive Therapy Status ", id: "" },
    { name: "Screened for T.B during the last visit ", id: "" },
    { name: "T. B Screening status ", id: "" },
    { name: "Current TB status", id: "" },
    { name: "On TB treatment(N/Y/NA)", id: "" },
    { name: "Has the person Disclosed or Disclosed to? Y/N", id: "" },
    { name: "EID No", id: "" },
    { name: "EID Enrollment date", id: "eidEnrollmentDate" },
    { name: "Mother's Name", id: "" },
    { name: "Mother's Art No", id: "" },
    { name: "Mother's Facility", id: "" },
    {
        name: "HEI up to date with Immunization schedule (check immunization/child health card): Y/N",
        id: "",
    },
    { name: "1st PCR Date", id: "dateFirstPCRDone" },
    { name: "1st PCR Results", id: "firstPCRResults" },
    { name: "2nd PCR Date", id: "dateSecondPCRDone" },
    { name: "2nd PCR Results", id: "secondPCRResults" },
    { name: "3rd PCR Date", id: "dateThirdPCRDone" },
    { name: "3rd PCR Results", id: "thirdPCRResults" },
    { name: "Due date for HIV rapid Test", id: "hivTestDueDate" },
    { name: "Date when HIV rapid test was done", id: "dateHivTestDone" },
    { name: "HIV test result", id: "hivTestResults" },
    { name: "Final Outcome", id: "finalOutcome" },
    { name: "PCR Test", id: "pcr" },
    { name: "Missed Appointment Date", id: "" },
    { name: "Missed Appointment in the Quarter", id: "" },
    { name: "Missed Appointment Reason", id: "" },
    { name: "Type of follow up", id: "" },
    { name: "Followup Outcome", id: "" },
    { name: "Ever Missed An Appointment in the Year", id: "" },
    { name: "VSLA", id: "" },
    { name: "VSLA Saving ", id: "" },
    { name: "VSLA Training", id: "" },
    { name: "Group Based Financial Literacy", id: "" },
    { name: "Bank Linkages", id: "" },
    { name: "Agribusiness", id: "" },
    { name: "SPM Training", id: "" },
    { name: "Micro Franchise", id: "" },
    { name: "IGA Booster", id: "" },
    { name: "Temporary Food support", id: "" },
    { name: "VSLA Borrowing", id: "" },
    { name: "VSLA OVC protection Fund", id: "" },
    { name: "Vocational/Apprenticeship", id: "" },
    { name: "Linked to Gvernment social protection programs", id: "" },
    { name: "Direct Beneficiaries operating an IGA", id: "" },
    {
        name: "Direct Beneficiaries operating an IGA registering success in their IGAs",
        id: "",
    },
    { name: "Output Markets", id: "" },
    { name: "CORE_ES", id: "" },
    { name: "Are you currently enrolled in school?", id: "" },
    { name: "Name of your current School", id: "" },
    { name: "In which Class are you in", id: "" },
    { name: "Monitored at school", id: "" },
    { name: "Education subsidy", id: "" },
    { name: "OVC VSLA Education Fund", id: "" },
    { name: "Scholastic Materials", id: "" },
    { name: "School Fees", id: "" },
    { name: "Supported to enrol in school", id: "" },
    { name: "CORE_EDUCATION", id: "" },
    { name: "VSLA OVC Health Fund", id: "" },
    { name: "HTS referral", id: "" },
    { name: "Non Disclosure Support", id: "" },
    { name: "Antiretroviral Therapy (ART) Initiation", id: "" },
    { name: "HCT/ Tested for HIV", id: "" },
    { name: "Attachment to CoRPS", id: "" },
    { name: "ART_Adherence_Education", id: "" },
    { name: "Caregiver/ Adolescent HIV care and treatment literacy", id: "" },
    { name: "Community Viral load Bleeding", id: "" },
    { name: "PLHIV Returned to Care", id: "" },
    { name: "Intensive Adherence Counseling (IAC)", id: "" },
    { name: "EMTCT", id: "" },
    { name: "HIV prevention Education", id: "" },
    { name: "Transport_Health", id: "" },
    { name: "PEP Service", id: "" },
    { name: "COVID 19 Education", id: "" },
    { name: "Linked to DSDM (MMD)", id: "" },
    { name: "DREAMS", id: "" },
    { name: "VMMC", id: "" },
    { name: "Appointment reminding", id: "" },
    { name: "Immunization Services", id: "" },
    { name: "Immunization Status", id: "" },
    { name: "WASH Services", id: "" },
    { name: "Insecticide Treated Nets", id: "" },
    { name: "Family Planning", id: "" },
    { name: "TB Screening", id: "" },
    { name: "Risk of TB", id: "" },
    { name: "Tested for TB", id: "" },
    { name: "Initiated on TB Treatment", id: "" },
    { name: "Supported to Complete TB Dose", id: "" },
    { name: "Other Health Related Services", id: "" },
    { name: "CORE_HEALTH", id: "" },
    { name: "GBV Prevention Education", id: "" },
    { name: "GBV Screening", id: "" },
    { name: "Reported GBV", id: "" },
    { name: "GBV counselling", id: "" },
    { name: "GBV_Referred for further support", id: "" },
    { name: "Emotional/psychological Abuse", id: "" },
    { name: "Physical Abuse", id: "" },
    { name: "Sexual Abuse", id: "" },
    { name: "IPV related to HIV status disclosure", id: "" },
    { name: "Transport_GBV", id: "" },
    { name: "Withdrawn from GBV affected Household", id: "" },
    { name: "GBV Legal support", id: "" },
    { name: "Basic needs", id: "" },
    { name: "CP Legal support", id: "" },
    { name: "RE Integartion", id: "" },
    { name: "Withdrawn from Child labor", id: "" },
    { name: "Assisted to handle Child abuse or neglect case", id: "" },
    { name: "Birth registration", id: "" },
    { name: "NMN (Boys)", id: "" },
    { name: "NMN Venue (e.g. Church/Community Ctr. Name )", id: "" },
    {
        name: "NMN Delivery Method [In School, After School, Out of School]",
        id: "",
    },
    { name: "NMN Group Name", id: "" },
    { name: "Attended ECD", id: "" },
    { name: "Completed ECD", id: "" },
    { name: "Attended SINOVUYO", id: "" },
    { name: "Completed SINOVUYO", id: "" },
    { name: "Child Protection Education", id: "" },
    { name: "CORE_CHILD PROTECTION", id: "" },
    { name: "Nutrition education", id: "" },
    { name: "Nutritional Assessment", id: "" },
    { name: "Nutrition Status ", id: "" },
    { name: "Voucher for crops", id: "" },
    { name: "Supported to estblish Kitchen Garden", id: "" },
    { name: "Nutritional Food Supplement", id: "" },
    { name: "Agricultural and farming inputs", id: "" },
    { name: "Agric Advisory service", id: "" },
    { name: "CORE_NUTRITION", id: "" },
    { name: "PSS", id: "" },
    { name: "Mental Health (E/P)", id: "" },
    { name: "Recreation Activities", id: "" },
    { name: "Will Writing", id: "" },
    { name: "Assistive devices", id: "" },
    { name: "CORE_PSS", id: "" },
    { name: "3 or More CPAS", id: "" },
    { name: "Served_in_Previous Quarter", id: "" },
    { name: "Pre /Graduated(1 Yes, 0 No)", id: "" },
    { name: "Fully Graduated(1 Yes, 0 No)", id: "" },
    { name: "OVC_SERV (Comprehensive)", id: "" },
    { name: "OVC_SERV PREV ", id: "" },
    { name: "Overall OVC_SERV (COMP+PREV) ", id: "" },
    { name: "OVC_ENROL", id: "" },
    { name: "OVC_SERV_SUBPOP", id: "" },
    { name: "OVC_HIV STAT (1 Yes, 0 No, )", id: "" },
    { name: "Asset Ownership", id: "" },
    { name: "Exited With Graduation", id: "" },
    { name: "Para-social Worker / NMN Instructor", id: "" },
    { name: "Telephone No. of Para /social Worker", id: "" },
];
