export const COLUMNS: Array<{
    id: string;
    display: string;
    selected: boolean;
}> = [
    { selected: true, display: "Beneficiary ID", id: "beneficiaryId" },
    { selected: true, display: "HouseHold Code", id: "householdCode" },
    { selected: true, display: "Enrollment Date", id: "enrollmentDate" },
    { selected: true, display: "Type(Comprehensive, Prevention)", id: "type" },
    { selected: true, display: "District/City", id: "district" },
    { selected: true, display: "Subcounty", id: "subCounty" },
    { selected: true, display: "Parish", id: "parish" },
    { selected: true, display: "Village", id: "village" },
    { selected: true, display: "Household Head", id: "householdHead" },
    { selected: true, display: "Primary Caregiver", id: "primaryCareGiver" },
    { selected: true, display: "Date of Assessment", id: "eventDate" },
    { selected: true, display: "Beneficiary Name", id: "beneficiaryName" },
    { selected: true, display: "DOB", id: "dob" },
    { selected: true, display: "Age", id: "age" },
    { selected: true, display: "Age Group", id: "ageGroup" },
    { selected: true, display: "Sex", id: "sex" },
    { selected: true, display: "Reason for visit", id: "reasonForVisit" },
    { selected: true, display: "Current Risk Factor", id: "riskFactor" },
    { selected: true, display: "Other Risk Factors", id: "otherRiskFactor" },
    {
        selected: true,
        display: "Current Household Economic Status ",
        id: "economicStatus",
    },
    { selected: true, display: "Household status", id: "householdStatus" },
    { selected: true, display: "Member status", id: "memberStatus" },
    {
        selected: true,
        display: "Currently Enrolled in School (Y/N) (Home visit)",
        id: "enrolledInSchool",
    },
    { selected: true, display: "Newly enrolled", id: "newlyEnrolledText" },
    { selected: true, display: "HIV_Status(+, /,?,  //+)", id: "hivStatus" },
    { selected: true, display: "OVC_TST ASSESS", id: "OVC_TST_ASSESS" },

    { selected: true, display: "OVC_TST RISK", id: "isAtRisk" },
    { selected: true, display: "OVC_TST REFER", id: "OVC_TST_REFER" },
    { selected: true, display: "OVC_TST REPORT", id: "OVC_TST_REPORT" },
    {
        selected: true,
        display: "HIV test not required based on  HIV risk Assessment",
        id: "testNotRequired",
    },
    {
        selected: true,
        display: "Unknown HIV status: other reasons",
        id: "unknown",
    },
    {
        selected: true,
        display: "Newly Reported HIV Positive (1 Yes, 0 No)",
        id: "newlyReportedPositive",
    },
    {
        selected: true,
        display: "Newly Tested HIV Positive (1 Yes, 0 No)",
        id: "newlyTestedPositive",
    },
    {
        selected: true,
        display: "Newly Tested HIV Positive initiated on ART (1 Yes, 0 No)",
        id: "newlyTestedAndOnArt",
    },

    { selected: true, display: "Date of ART initiation", id: "artStartDate" },
    { selected: true, display: "Facility", id: "facility" },
    {
        selected: true,
        display: "Last Viral Load Date",
        id: "lastViralLoadDate",
    },
    {
        selected: true,
        display: "Date when Next VL test will be done",
        id: "nextViralLoadDate",
    },
    { selected: true, display: "Regimen", id: "regimen" },
    { selected: true, display: "On_ART_VL (1 Yes, 0 No)", id: "onArt" },
    {
        selected: true,
        display: "CLHIV/OVC_VL Eligible (1 Yes,0 No)",
        id: "ovcEligible",
    },
    {
        selected: true,
        display: "ALHIV_VL Eligible (1 Yes,0 No)",
        id: "alHivEligible",
    },
    {
        selected: true,
        display: "Viral Load Status (Suppressed, Non Suppressed, Waiting)",
        id: "viralLoadStatus",
    },
    { selected: true, display: "Viral Load Copies", id: "viralLoadCopies" },
    {
        selected: true,
        display: "Low Viremia   [201 Cc pl/400dbs-999]",
        id: "lowViremia",
    },
    {
        selected: true,
        display: "High Viremia High Viremia [>1,000 cml]",
        id: "highViremia",
    },
    {
        selected: true,
        display: "OVC_VLR (1 Yes, 0 No, Waiting )",
        id: "viralLoadResultsReceived",
    },
    { selected: true, display: "OVC_VLS (1 Yes, 0 No))", id: "VLSuppressed" },

    { selected: true, display: "EID No", id: "eidNo" },
    { selected: true, display: "EID Enrollment date", id: "eidEnrollmentDate" },
    { selected: true, display: "Mother's Art No", id: "motherArtNo" },
    { selected: true, display: "1st PCR Date", id: "dateFirstPCRDone" },
    { selected: true, display: "1st PCR Results", id: "firstPCRResults" },
    { selected: true, display: "2nd PCR Date", id: "dateSecondPCRDone" },
    { selected: true, display: "2nd PCR Results", id: "secondPCRResults" },
    { selected: true, display: "3rd PCR Date", id: "dateThirdPCRDone" },
    { selected: true, display: "3rd PCR Results", id: "thirdPCRResults" },
    {
        selected: true,
        display: "Due date for HIV rapid Test",
        id: "hivTestDueDate",
    },
    { selected: true, display: "HIV test result", id: "hivTestResults" },
    { selected: true, display: "Final Outcome", id: "finalOutcome" },
    { selected: true, display: "PCR Test", id: "PCRTest" },
    {
        selected: true,
        display: "Missed Appointment Date",
        id: "missedAppointmentDate",
    },
    {
        selected: true,
        display: "Missed Appointment Reason",
        id: "missedAnAppointmentReason",
    },
    { selected: true, display: "Type of follow up", id: "followupType" },
    {
        selected: true,
        display: "Followup Outcome",
        id: "missedAnAppointmentFollowupOutcome",
    },
    { selected: true, display: "VSLA", id: "VSLA" },
    {
        selected: true,
        display: "Home Based Financial Literacy",
        id: "VSLASavings",
    },
    // { selected: true, display: "VSLA Training", id: "VSLATraining" },
    { selected: true, display: "Group Based Financial Literacy", id: "" },
    { selected: true, display: "Bank Linkages", id: "bankLinkages" },
    { selected: true, display: "Agribusiness", id: "agricLinkages" },
    { selected: true, display: "SPM Training", id: "SPMTraining" },
    { selected: true, display: "Micro Franchise", id: "microFranchise" },
    { selected: true, display: "IGA", id: "iga" },
    { selected: true, display: "IGA Booster", id: "igaBooster" },
    {
        selected: true,
        display: "Temporary Food support",
        id: "tempConsumption",
    },
    // { selected: true, display: "VSLA Borrowing", id: "VSLABorrowing" },
    {
        selected: true,
        display: "VSLA OVC protection Fund",
        id: "ovcProtectionFunds",
    },

    {
        selected: true,
        display: "Vocational/Apprenticeship",
        id: "apprenticeship",
    },
    // {
    //     selected: true,
    //     display: "Linked to Gvernment social protection programs",
    //     id: "governmentSocialProtection",
    // },
    // {
    //     selected: true,
    //     display: "Direct Beneficiaries operating an IGA",
    //     id: "operatingAnIGA",
    // },
    // {
    //     selected: true,
    //     display:
    //         "Direct Beneficiaries operating an IGA registering success in their IGAs",
    //     id: "igaRegisteringSuccess",
    // },
    // { selected: true, display: "Output Markets", id: "outputMarkets" },
    { selected: true, display: "CORE_ES", id: "coreES" },
    // {
    //     selected: true,
    //     display: "Ever Missed An Appointment in the Year",
    //     id: "hasEverMissedAnAppointment",
    // },

    // {
    //     selected: true,
    //     display: "On multi month Dispensing (MMD) Y/N",
    //     id: "onMultiMonthDispensing",
    // },
    // { selected: true, display: "Client DSD model", id: "clientDSDModel" },
    // {
    //     selected: true,
    //     display: "Client TB Preventive Therapy Status ",
    //     id: "currentTBPreventionStatus",
    // },
    // {
    //     selected: true,
    //     display: "Screened for T.B during the last visit ",
    //     id: "screened4TB",
    // },
    // {
    //     selected: true,
    //     display: "T. B Screening status ",
    //     id: "tbScreeningStatus",
    // },
    // { selected: true, display: "Current TB status", id: "currentTBStatus" },
    // { selected: true, display: "On TB treatment(N/Y/NA)", id: "onTBTreatment" },
    // {
    //     selected: true,
    //     display: "Has the person Disclosed or Disclosed to? Y/N",
    //     id: "hasThePersonDisclosed",
    // },

    // {
    //     selected: true,
    //     display: "Are you currently enrolled in school? (School Mapping)",
    //     id: "enrolledAtSchool",
    // },
    // {
    //     selected: true,
    //     display: "Name of your current School",
    //     id: "currentSchool",
    // },
    // {
    //     selected: true,
    //     display: "In which Class are you in",
    //     id: "currentClass",
    // },
    // {
    //     selected: true,
    //     display: "Monitored at school",
    //     id: "monitoringAtSchool",
    // },
    // {
    //     selected: true,
    //     display: "Regularly attending school",
    //     id: "regularlyAttendingSchool",
    // },
    { selected: true, display: "Education subsidy", id: "educationSubsidy" },
    { selected: true, display: "Home learning", id: "homeLearning" },
    {
        selected: true,
        display: "Vocational/Apprenticeship",
        id: "apprenticeship",
    },
    {
        selected: true,
        display:
            "Education Information (Enrollment, Attendance, Retention and Progression)",
        id: "educationInformation",
    },

    { selected: true, display: "OVC VSLA Education Fund", id: "educationFund" },
    { selected: true, display: "Education", id: "education" },
    {
        selected: true,
        display: "Mode of studying (Boarding or Day)",
        id: "studyMode",
    },
    // {
    //     selected: true,
    //     display: "Scholastic Materials",
    //     id: "scholasticMaterials",
    // },
    // { selected: true, display: "School Fees", id: "schoolFees" },
    // {
    //     selected: true,
    //     display: "Supported to enrol in school",
    //     id: "supportedToEnroll",
    // },
    { selected: true, display: "CORE EDUCATION", id: "coreEducation" },
    { selected: true, display: "VSLA OVC Health Fund", id: "healthFund" },
    { selected: true, display: "HTS referral", id: "HTSReferral" },
    {
        selected: true,
        display: "Non Disclosure Support",
        id: "nonDisclosureSupport",
    },
    {
        selected: true,
        display: "Antiretroviral Therapy (ART) Initiation",
        id: "artInitiation",
    },
    {
        selected: true,
        display: "Home drug delivery",
        id: "homeDrugDelivery",
    },
    // { selected: true, display: "HCT/ Tested for HIV", id: "testedForHIV" },
    // { selected: true, display: "Attachment to CoRPS", id: "attachedToCorps" },
    {
        selected: true,
        display: "ART Adherence Education",
        id: "artAdherenceEducation",
    },
    // {
    //     selected: true,
    //     display: "Caregiver/ Adolescent HIV care and treatment literacy",
    //     id: "hivCareAndLiteracy",
    // },
    {
        selected: true,
        display: "Community Viral load Bleeding",
        id: "communityViralLoadBleeding",
    },
    { selected: true, display: "PLHIV Returned to Care", id: "returnedToCare" },
    {
        selected: true,
        display: "Intensive Adherence Counseling (IAC)",
        id: "iac",
    },
    { selected: true, display: "CAGDOTs (Yes=1,No=0)", id: "gagaDot" },
    { selected: true, display: "EMTCT", id: "eMTCT" },
    {
        selected: true,
        display: "HIV prevention Education",
        id: "hivPrevention",
    },
    { selected: true, display: "Journeys MoH", id: "journeysMOH" },
    { selected: true, display: "Journeys LARA", id: "journeysLARA" },
    { selected: true, display: "NMN (Boys)", id: "NMNBoys" },
    { selected: true, display: "NMN (Girls)", id: "NMNGirls" },
    {
        selected: true,
        display: "Mental Health Services",
        id: "mentalHealthServices",
    },
    { selected: true, display: "Transport Health", id: "TFHealth" },
    { selected: true, display: "PEP Service", id: "PEP" },
    { selected: true, display: "COVID 19 Education", id: "covid19Education" },
    { selected: true, display: "Immunization Services", id: "immunization" },
    { selected: true, display: "WASH Services", id: "wash" },
    { selected: true, display: "Insecticide Treated Nets", id: "treatedNets" },
    { selected: true, display: "Family Planning", id: "familyPlanning" },
    // { selected: true, display: "DREAMS", id: "dreams" },
    // { selected: true, display: "VMMC", id: "vmmc" },
    // {
    //     selected: true,
    //     display: "Appointment reminding",
    //     id: "appointmentReminding",
    // },
    { selected: true, display: "TB Screening", id: "tbScreening" },
    { selected: true, display: "Risk of TB", id: "atRiskOfTB" },
    { selected: true, display: "Tested for TB", id: "tested4TB" },
    {
        selected: true,
        display: "Initiated on TB Treatment",
        id: "initiatedOnTB",
    },
    {
        selected: true,
        display: "TB Treatment start date",
        id: "initiatedOnTB",
    },
    {
        selected: true,
        display: "Supported to Complete TB Dose",
        id: "supported2CompleteTBDose",
    },
    // {
    //     selected: true,
    //     display: "Other Health Related Services",
    //     id: "otherHealthServices",
    // },
    { selected: true, display: "CORE_HEALTH", id: "coreHealth" },
    { selected: true, display: "GBV Prevention Education", id: "GBVEduction" },
    { selected: true, display: "Transport_GBV", id: "TFGBV" },
    { selected: true, display: "GBV Legal support", id: "GBVLegalSupport" },
    { selected: true, display: "Completed ECD", id: "completedECD" },
    { selected: true, display: "Attended Parenting", id: "attendedParenting" },
    {
        selected: true,
        display: "Completed Parenting",
        id: "completedParenting",
    },
    {
        selected: true,
        display: "Child Protection Education",
        id: "childProtectionEducation",
    },
    // { selected: true, display: "GBV Screening", id: "hasGbvScreening" },
    // { selected: true, display: "Reported GBV", id: "reportedGBV" },
    // { selected: true, display: "GBV counselling", id: "GBVCounseling" },
    // {
    //     selected: true,
    //     display: "GBV Referred for further support",
    //     id: "GBVReferral",
    // },
    // {
    //     selected: true,
    //     display: "Emotional/psychological Abuse",
    //     id: "emotionalAbuse",
    // },
    // { selected: true, display: "Physical Abuse", id: "physicalAbuse" },
    // { selected: true, display: "Sexual Abuse", id: "sexualAbuse" },
    // {
    //     selected: true,
    //     display: "IPV related to HIV status disclosure",
    //     id: "IPVHIVDisclosure",
    // },
    // {
    //     selected: true,
    //     display: "Withdrawn from GBV affected Household",
    //     id: "withdrawnFromGVBHousehold",
    // },
    // { selected: true, display: "Basic needs", id: "basicNeed" },
    // {
    //     selected: true,
    //     display: "Basic needs(Direct Beneficiary)",
    //     id: "basicNeedsDirect",
    // },
    // {
    //     selected: true,
    //     display: "Child Protection Legal support",
    //     id: "legalSupport",
    // },
    // { selected: true, display: "RE Integration", id: "reIntegration" },
    // {
    //     selected: true,
    //     display: "Withdrawn from Child labor",
    //     id: "withdrawFromLabour",
    // },
    // {
    //     selected: true,
    //     display: "Assisted to handle Child abuse or neglect case",
    //     id: "handleChildAbuse",
    // },
    // { selected: true, display: "Birth registration", id: "birthRegistration" },
    // { selected: true, display: "NMN (Boys)", id: "NMNBoys" },
    // {
    //     selected: true,
    //     display: "NMN Venue (e.g. Church/Community Ctr. Name )",
    //     id: "NMNVenue",
    // },
    // {
    //     selected: true,
    //     display: "NMN Delivery Method [In School, After School, Out of School]",
    //     id: "NMNDeliveryMethod",
    // },
    // { selected: true, display: "NMN Group Name", id: "NMNGroupName" },
    // { selected: true, display: "Attended ECD", id: "AttendedECD" },
    // { selected: true, display: "Attended SINOVUYO", id: "attendedSinovuyo" },
    // { selected: true, display: "Completed SINOVUYO", id: "completedSinovuyo" },

    {
        selected: true,
        display: "CORE CHILD PROTECTION",
        id: "coreChildProtection",
    },

    {
        selected: true,
        display: "Nutrition education",
        id: "nutritionEducation",
    },
    { selected: true, display: "Voucher for crops", id: "voucher4Crops" },
    {
        selected: true,
        display: "Nutritional Support (Kitchen Garden)",
        id: "kitchenGarden ",
    },

    {
        selected: true,
        display: "Nutritional Assessment",
        id: "nutritionalAssessment",
    },
    {
        selected: true,
        display: "Nutritional Food Supplement",
        id: "nutritionalFoodSupplement",
    },
    // {
    //     selected: true,
    //     display: "Nutrition Status ",
    //     id: "nutritionalStatus",
    // },
    // {
    //     selected: true,
    //     display: "Supported to establish Kitchen Garden",
    //     id: "kitchenGarden",
    // },

    // {
    //     selected: true,
    //     display: "Agricultural and farming inputs",
    //     id: "farmingInputs",
    // },
    // {
    //     selected: true,
    //     display: "Agric Advisory service",
    //     id: "agricAdvisoryService",
    // },
    { selected: true, display: "CORE_NUTRITION", id: "coreNutrition" },
    { selected: true, display: "PSS", id: "psychosocialSupport" },
    // { selected: true, display: "Mental Health (E/P)", id: "mentalHealth" },
    // {
    //     selected: true,
    //     display: "Recreation Activities",
    //     id: "recreationActivities",
    // },
    // { selected: true, display: "Will Writing", id: "willWriting" },
    // { selected: true, display: "Assistive devices", id: "assistiveDevices" },
    { selected: true, display: "CORE_PSS", id: "corePSS" },
    {
        selected: true,
        display: "Served in Previous Quarter",
        id: "servedInPreviousQuarter",
    },
    {
        selected: true,
        display: "Served in Current Quarter",
        id: "servedInCurrentQuarter",
    },
    { selected: true, display: "DSDM", id: "linkedToDSDM" },
    { selected: true, display: "TPT", id: "tpt" },

    {
        selected: true,
        display: "Pre /Graduated(1 Yes, 0 No)",
        id: "preGraduated",
    },

    {
        selected: true,
        display: "Benchmark 1: HIV Status (or test Not required)",
        id: "benchmark1",
    },
    {
        selected: true,
        display: "Benchmark 2: Virally suppressed ",
        id: "benchmark2",
    },
    {
        selected: true,
        display:
            "Benchmark 3: Knowledgeable about HIV prevention (Skip if No 09-17 year Old in HH)",
        id: "benchmark3",
    },
    {
        selected: true,
        display:
            "Benchmark 4. Not undernourished (Skip if No child aged 6-59 months (4.9 years))",
        id: "benchmark4",
    },
    {
        selected: true,
        display: "Benchmark 5. Improved financial stability",
        id: "benchmark5",
    },
    {
        selected: true,
        display: "Benchmark 6. No Violence",
        id: "benchmark6",
    },
    {
        selected: true,
        display: "Benchmark 7. No Child Headed Household",
        id: "benchmark7",
    },
    {
        selected: true,
        display: "Benchmark 8. Children in School",
        id: "benchmark8",
    },

    {
        selected: true,
        display: "Fully Graduated(1 Yes, 0 No)",
        id: "fullyGraduated",
    },
    { selected: true, display: "OVC_SERV (Comprehensive)", id: "OVC_SERV" },
    {
        selected: true,
        display: "OVC_SERV (18-20) with skilling + Education subsidy",
        id: "OVC_SERV",
    },
    { selected: true, display: "DREAMS Overlap", id: "dreams" },
    { selected: true, display: "3 or More CPAS", id: "CPas" },
    // { selected: true, display: "OVC_SERV PREV ", id: "OVC_SERV_PREV" },
    // {
    //     selected: true,
    //     display: "Overall OVC_SERV (COMP+PREV) ",
    //     id: "OVC_SERV_OVERALL",
    // },
    { selected: true, display: "OVC_ENROL", id: "OVC_ENROL" },
    { selected: true, display: "OVC_SERV_SUBPOP", id: "OVC_SERV_SUBPOP" },
    {
        selected: true,
        display: "OVC_HIV STAT (1 Yes, 0 No, )",
        id: "OVC_HIV_STAT",
    },
    {
        selected: true,
        display: "OVC_HIV STAT < 18",
        id: "OVC_HIV_STAT_L18",
    },
    {
        selected: true,
        display: "OVC_HIV STAT 18+",
        id: "OVC_HIV_STAT_18",
    },
    { selected: true, display: "Asset Ownership", id: "assetOwnership" },
    {
        selected: true,
        display: "Exited With Graduation",
        id: "exitedWithGraduation",
    },
    {
        selected: true,
        display: "Exited Without Graduation Status",
        id: "exitedWithoutGraduation",
    },
    {
        selected: true,
        display: "Transferred to other IP",
        id: "transferred",
    },
    {
        selected: true,
        display: "Para-social Worker Name",
        id: "NMNInstructor",
    },
    {
        selected: true,
        display: "Para-social Worker Contact",
        id: "paraSocialWorker",
    },

    {
        selected: true,
        display: "CLHIV Disclosed to",
        id: "clhivDisclosedTo",
    },
    {
        selected: true,
        display: "Mental Health Screening",
        id: "mentalHealthScreening",
    },
    {
        selected: true,
        display: "Anxiety or Depression (1,0)",
        id: "anxietyDepression",
    },
    {
        display: "Data Entrant",
        id: "dataEntrant",
        selected: true,
    },
    {
        selected: true,
        display: "Mental Health Services Provided",
        id: "mentalHealthServices",
    },
    { selected: true, display: "GBV Screening", id: "hasGbvScreening" },
    { selected: true, display: "GBV Cases", id: "hasGbvCases" },
    { selected: true, display: "SGBV Cases", id: "hasSGbvCases" },
    {
        selected: true,
        display: "GBV Services Provided",
        id: "gbvServicesProvided",
    },
    {
        selected: true,
        display: "Post Disclosure",
        id: "postDisclosure",
    },
    {
        selected: true,
        display: "Post Disclosure # of sessions",
        id: "postDisclosureSessions",
    },
    {
        selected: true,
        display: "School Mapping",
        id: "schoolMapping",
    },
    {
        selected: true,
        display: "Currently in School(1, 0)",
        id: "currentlyInSchool",
    },
    {
        selected: true,
        display: "Levels of education",
        id: "levelsOfEducation",
    },
];
